Handle envir
rstudio/plumber pull request #677
Opened 2020-09-21 20:52 UTC by meztez

Brief description of the original problem and the approach behind your solution.

#676 

PR task list:
- [ ] Update NEWS
- [ ] Add tests
- [x] Update documentation with `devtools::document()`

2020-09-22 14:39 UTC, schloerke requested changes

2020-09-22 14:39 UTC, schloerke commented on R/plumber.R
> +    #' @param ... additional arguments for [PlumberEndpoint] `new` method (namely `lines`, `params`, `comments`, `responses` and `tags`).
```suggestion
    #' @param ... additional arguments for [PlumberEndpoint] `new` method (namely `lines`, `params`, `comments`, `responses` and `tags`. Excludes `envir`).
```

2020-09-22 14:39 UTC, schloerke commented on R/plumber.R
> +    handle = function(methods, path, handler, preempt, serializer, parsers, endpoint, environment, ...) {
```suggestion
    handle = function(methods, path, handler, preempt, serializer, parsers, endpoint, ...) {
```

2020-09-22 14:39 UTC, schloerke commented on R/plumber.R
> +        }
```suggestion
        if ("envir" %in% names(list(...))) {
          stop("`envir` can not be supplied to `pr$handle()`")
        }
```

2020-09-22 14:39 UTC, schloerke commented on R/plumber.R
> +                                        envir = environment,
```suggestion
                                        envir = private$envir,
```

2020-09-22 14:39 UTC, schloerke commented on NEWS.md
> +* Something about how handle deals with ... in relation to PlumberEndpoint
```suggestion
* When manually calling a new `Plumber` `handle()`, `envir` may not be supplied when defining a new `PlumberEndpoint` #677  
```

2020-09-22 14:39 UTC, schloerke commented on R/plumber.R
> +        }
Could you add a test for this stop situation? Thank you!

2020-09-22 15:26 UTC, schloerke commented on NEWS.md
> +* When manually calling `Plumber$handle()`, `envir` may not be passed through when defining a new `PlumberEndpoint` #677
```suggestion
* When calling `Plumber$handle()` and defining a new `PlumberEndpoint`, `...` will be checked for invalid names #677  
```

2020-09-22 16:06 UTC, schloerke approved these changes

2020-09-24 21:42 UTC, cpsievert approved these changes

2020-09-25 21:36 UTC, merged