avoid print mount recursion fix #592
rstudio/plumber pull request #683
Opened 2020-10-01 22:30 UTC by meztez

Minimal reproducible example

#592
PR task list:
- [x] Update NEWS
- [x] Add tests
- [x] Update documentation with `devtools::document()`

2020-10-09 12:52 UTC, schloerke requested changes

2020-10-09 12:52 UTC, schloerke commented on NEWS.md
> +* When calling `print` on router, detect mount recursion and exit early #683
```suggestion
* When calling `print` on router, detect mount recursion and exit early (@meztez, #683)
```

2020-10-09 12:52 UTC, schloerke commented on R/plumber.R
> +        cat(prefix, "# Circular reference detected", "\n", sep="")
```suggestion
        cat(prefix, "# Circular Plumber reference detected", "\n", sep="")
```

2020-10-09 12:52 UTC, schloerke commented on tests/testthat/test-plumber-print.R
> +  expect_match(printed3, "Circular reference detected", all = FALSE)
```suggestion
  expect_match(printed, "Circular Plumber reference detected", all = FALSE)
  expect_match(printed3, "Circular Plumber reference detected", all = FALSE)
```

2020-10-09 13:15 UTC, schloerke approved these changes

2020-10-15 20:21 UTC, cpsievert approved these changes
If you want, it might be nice to have a different color for the circular ref message

2020-10-15 23:18 UTC, meztez commented
> If you want, it might be nice to have a different color for the circular ref message

Any color you fancy?

2020-12-16 04:18 UTC, meztez commented
currentyl using  `printing`, maybe use flag facility when implemented.

2020-12-29 23:22 UTC, schloerke commented
Closing in favor of #738

2020-12-29 23:22 UTC, closed without merging