force error response body json serialization (fix #688)
rstudio/plumber pull request #689
Opened 2020-10-06 17:10 UTC by meztez

See #688 

PR task list:
- [x] Update NEWS
- [x] Add tests
- [x] Update documentation with `devtools::document()`

2020-10-09 12:50 UTC, schloerke requested changes

2020-10-09 12:50 UTC, schloerke commented on NEWS.md
> +* Force json serialization of endpoint error responses #689
```suggestion
* When calling `Plumber$handle()` and defining a new `PlumberEndpoint`, `...` will be checked for invalid names (@meztez, #677)
* Force json serialization of endpoint error responses (@meztez, #689)
```

2020-10-09 13:14 UTC, schloerke approved these changes

2020-10-15 20:27 UTC, cpsievert commented on R/default-handlers.R
> +      res$serializer <- serializer_unboxed_json()
Let's add a note of a breaking change (in the news) about the serializer change

2020-10-15 20:30 UTC, cpsievert approved these changes

2020-12-29 18:21 UTC, merged