Un-deprecate run(swaggerCallback=), add run(quiet=) param
rstudio/plumber pull request #765
Opened 2021-02-07 00:01 UTC by jcheng5

To better support headless running scenarios

## Pull Request

Before you submit a pull request, please do the following:

* Add an entry to NEWS concisely describing what you changed.

* Add unit tests in the tests/testthat directory.

* Run Build->Check Package in the RStudio IDE, or `devtools::check()`, to make sure your change did not add any messages, warnings, or errors.

Doing these things will make it easier for the plumber development team to evaluate your pull request. Even so, we may still decide to modify your code or even not merge it at all. Factors that may prevent us from merging the pull request include:

* breaking backward compatibility
* adding a feature that we do not consider relevant for plumber
* is hard to understand
* is hard to maintain in the future
* is computationally expensive
* is not intuitive for people to use

We will try to be responsive and provide feedback in case we decide not to merge your pull request.

## Minimal reproducible example

Finally, please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.
```r
reprex::reprex({
  library(plumber)
  # insert reprex here

})
```

Delete these instructions once you have read them.

---

Brief description of the original problem and the approach behind your solution.

```r
# insert reprex here
```

PR task list:
- [ ] Update NEWS
- [ ] Add tests
- [ ] Update documentation with `devtools::document()`

2021-02-07 04:29 UTC, meztez commented
This would probably work too
```r
pr() %>% pr_set_docs_callback(NULL) %>% pr_run(quiet = TRUE)
```

It made realize `options_plumber` needs to handle deprecated option `plumber.swagger.url` so we could do

```r
options_plumber(docs.callback = NULL) # Whole session
pr() %>% pr_run(quiet = TRUE)
```

As it is we still default to it when initializing the router.

I liked the idea of distanciating the package from the swagger ui by using more general names.

2021-02-08 15:57 UTC, schloerke commented
@jcheng5 `@meztez` has a fix for the `docs.callback` option for a global session. (PR fix: https://github.com/rstudio/plumber/pull/766). I'd prefer to not un-deprecate `pr_run(swaggerCallback=)` and use `pr_set_docs_callback(NULL)` instead.

--------------------------

Would Connect ever want access to `pr_run(quiet=)`? Do you think we should allow users to ever receive the httpuv server to do as they please?

If no, then it seems like an appropriate place to put the `quiet=` argument (and end of the PR). If yes, then we should prolly make a `pr_set_httpuv(quiet = FALSE, sync = TRUE)` like method to do this before the `pr_run()` call.
* `quiet` to turn off printing
* `method` to switch between `httpuv::runServer()`, `httpuv::startServer()`, or return the server before starting. This parameter will take more implementation thought to make sure all existing assumptions (such as any `on.exit()` call) are covered.

While we do not need to implement the `method` parameter. I'd like to put the `quiet` parameter in an appropriate spot with room to grow.

2021-02-11 18:32 UTC, schloerke commented
Talking more with `@wch`, the httpuv methods and alterations would prolly be done best with a method outside of `pr_run()`.

Might be good to add a `pr_build()` which preps the plumber router and `pr_run()` would wrap `pr_build()` and then call `httpuv::runServer()`. For the concept of using different `httpuv` methods, it would require an update to `httpuv` such as adding a `app$onAppStop(fn)` (similar to `app$onWSClose()`). 

-------------

tl/dr; Put quiet in `pr_run(quiet=)` and `httpuv` related things could be added in new methods.

2021-02-11 18:34 UTC, meztez commented
Running an headless plumber would make a lot of people happy.

2021-02-11 18:41 UTC, schloerke requested changes
I believe this should revert the swaggerCallback changes and also insert `...` so that `quiet` must be full named.

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
> +    #'   ready. If missing, defaults to `$setDocsCallback()`.
```suggestion
    #' @param swaggerCallback Deprecated. See `$setDocsCallback()`
```

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
> +      swaggerCallback,
Add in `...`
```suggestion
      swaggerCallback = deprecated(),
      ...,
```

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
> +        swaggerCallback <- private$docs_callback
```suggestion
      if (lifecycle::is_present(swaggerCallback)) {
        lifecycle::deprecate_warn("1.0.0", "run(swaggerCallback = )", "setDocsCallback(callback = )")
        self$setDocsCallback(swaggerCallback)
```

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
> +          callback = swaggerCallback,
```suggestion
          callback = private$docs_callback,
```

2021-02-11 18:41 UTC, schloerke commented on R/pr.R
> +#'   missing, defaults to `$setDocsCallback()`.
```suggestion
```

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
> +    #' @param quiet If `TRUE`, don't print routine startup messages.
```suggestion
    #' @param ... Should be empty
    #' @param quiet If `TRUE`, don't print routine startup messages.
```

2021-02-11 18:41 UTC, schloerke commented on R/plumber.R
>        if (isTRUE(private$disable_run)) {
Make sure the dots are empty

```suggestion
      ellipsis::check_dots_empty()
      
      if (isTRUE(private$disable_run)) {
```

2021-02-11 18:41 UTC, schloerke commented on R/pr.R
> +#' @param quiet If `TRUE`, don't print routine startup messages.
```suggestion
#' @param ... Should be empty.
#' @param quiet If `TRUE`, don't print routine startup messages.
```

2021-02-11 18:41 UTC, schloerke commented on R/pr.R
> +                   swaggerCallback,
```suggestion
                   ...,
```

2021-02-11 18:41 UTC, schloerke commented on R/pr.R
>    validate_pr(pr)
```suggestion
  ellipsis::check_dots_empty()
  validate_pr(pr)
```

2021-02-11 18:41 UTC, schloerke commented on R/pr.R
> +         swaggerCallback = swaggerCallback,
```suggestion
```

2021-02-11 18:41 UTC, schloerke commented on NEWS.md
> +* Added `quiet = TRUE` to `Plumber$run()` to suppress routine startup messages. (@jcheng5 #765)
```suggestion
* Added `quiet = TRUE` to `pr_run()` and `Plumber$run()` to suppress routine startup messages. (@jcheng5 #765)
```

2021-02-26 20:56 UTC, schloerke commented
I am going to resolve all requested changes above as they are not to be used.

2021-03-01 18:36 UTC, jcheng5 commented on NEWS.md
> +  * Setting `swaggerCallback` to a function which will be called with a url to the documentation. See `pr_set_docs_callback()`.
```suggestion
  * Set `swaggerCallback` to a function which will be called with a url to the documentation, or `NULL` to do nothing. See `pr_set_docs_callback()`.
```

2021-03-01 18:58 UTC, jcheng5 commented on R/pr.R
> +#'     # turn of visual documentation
```suggestion
#'     # turn off visual documentation
```

2021-03-01 19:00 UTC, jcheng5 commented
LGTM!

2021-03-01 22:06 UTC, merged