Tweak Dockerfile; Reduce final size
rstudio/plumber pull request #871
Opened 2022-07-12 15:55 UTC by eitsupi

- Use the `org.opencontainers.image.authors` annotation instead of the `maintainer` label. (See <https://docs.docker.com/engine/reference/builder/#maintainer-deprecated>)
- Remove temp files to reduce image size. (c.f. Dockerfile best practices <https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run>)
  - `apt`'s cache `/var/lib/apt/lists/*`
  - `install2.r`'s cache `/tmp/downloaded_packages`
- Fix docs link

2022-07-13 17:12 UTC, schloerke requested changes
@eitsupi Awesome! Can you add two comments about the two `rm -rf` statements? I can see them performing them in the docs, but I don't immediately see what it is for.

Thank you!

2022-07-14 13:22 UTC, eitsupi commented
> Can you add two comments about the two `rm -rf` statements?

I updated the PR comment, but I didn't know what you wanted.
Do "two comments" mean comments in the source code?

2022-07-14 18:59 UTC, schloerke commented on Dockerfile
> +RUN install2.r --error --skipinstalled --ncpus -1 \
Add Dockerfile comment here about the `rm -rf`

2022-07-14 18:59 UTC, schloerke commented on Dockerfile
>  RUN apt-get update -qq && apt-get install -y --no-install-recommends \
Add Dockerfile comment here about the `rm -rf`

2022-07-14 19:01 UTC, schloerke commented on Dockerfile
>  RUN apt-get update -qq && apt-get install -y --no-install-recommends \
```suggestion

# `rm` call removes `apt` cache
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
```

2022-07-14 19:03 UTC, schloerke commented on Dockerfile
> +RUN install2.r --error --skipinstalled --ncpus -1 \
```suggestion
# `rm` call removes install2.r's cache
RUN install2.r --error --skipinstalled --ncpus -1 \
```

2022-07-14 19:04 UTC, schloerke approved these changes

2022-07-14 19:54 UTC, merged

2022-07-14 19:56 UTC, schloerke commented
Thank you!